#language: bash
language: node_js

node_js: '10.15.1'

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq jq

install:
 - npm install bats

script:
 - COMMAND=scripts/docker-image-size-curl.sh /usr/bin/time node_modules/bats/bin/bats test/*.bats
 - COMMAND=scripts/docker-image-size-reg.sh /usr/bin/time node_modules/bats/bin/bats test/*.bats
 - COMMAND=scripts/docker-image-size-docker.sh /usr/bin/time node_modules/bats/bin/bats test/*.bats