#language: bash
language: node_js

node_js: '10.15.1'

before_install:
 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 - sudo apt-get update
 - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
 - sudo apt-get install -qq jq
# Fix "open /etc/docker/certs.d/...: permission denied" for gcr, mcr, quay, etc.
 - sudo chmod o+x /etc/docker

install:
 - npm install bats

script:
 - COMMAND=scripts/docker-image-size-curl.sh /usr/bin/time node_modules/bats/bin/bats test/*.bats
 - COMMAND=scripts/docker-image-size-reg.sh /usr/bin/time node_modules/bats/bin/bats test/*.bats
 - COMMAND=scripts/docker-image-size-docker.sh /usr/bin/time node_modules/bats/bin/bats test/*.bats